/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactSection: typeof import('./src/components/ContactSection.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RepoGallery: typeof import('./src/components/RepoGallery.vue')['default']
    Services: typeof import('./src/components/Services.vue')['default']
    SocialProof: typeof import('./src/components/SocialProof.vue')['default']
    TechStack: typeof import('./src/components/TechStack.vue')['default']
    Testimonials: typeof import('./src/components/Testimonials.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
  }
}
