/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./src/components/AboutSection.vue')['default']
    AchievementCard: typeof import('./src/components/parts/AchievementCard.vue')['default']
    AchievementsSection: typeof import('./src/components/AchievementsSection.vue')['default']
    ContactSection: typeof import('./src/components/ContactSection.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ProjectCard: typeof import('./src/components/parts/ProjectCard.vue')['default']
    ProjectsSection: typeof import('./src/components/ProjectsSection.vue')['default']
    RepoGallery: typeof import('./src/components/RepoGallery.vue')['default']
    SectionState: typeof import('./src/components/ui/SectionState.vue')['default']
    ServiceCard: typeof import('./src/components/parts/ServiceCard.vue')['default']
    Services: typeof import('./src/components/Services.vue')['default']
    ServicesSection: typeof import('./src/components/ServicesSection.vue')['default']
    Skeleton: typeof import('./src/components/ui/Skeleton.vue')['default']
    SocialProof: typeof import('./src/components/SocialProof.vue')['default']
    TechStack: typeof import('./src/components/TechStack.vue')['default']
    TestimonialCard: typeof import('./src/components/parts/TestimonialCard.vue')['default']
    Testimonials: typeof import('./src/components/Testimonials.vue')['default']
    TestimonialsSection: typeof import('./src/components/TestimonialsSection.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    TimelineSection: typeof import('./src/components/TimelineSection.vue')['default']
  }
}
