name: Build Legal Public

on:
  push:
    paths:
      - "content/legal/**/*.md"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-legal-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Install deps
        run: |
          npm ci || npm i

      - name: Build Public from Markdown
        run: |
          npm run build:legal

      - name: Commit Public
        run: |
          if ! git status --porcelain | grep -q . ; then
            echo "No changes to commit"
            exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/legal
          git commit -m "chore(legal): update Public"
          git push
